Mox.defmock(ManMock, for: EHealth.API.ManBehaviour)
Mox.defmock(MPIMock, for: EHealth.API.MPIBehaviour)
Mox.defmock(MithrilMock, for: EHealth.API.MithrilBehaviour)
Mox.defmock(SignatureMock, for: EHealth.API.SignatureBehaviour)
Mox.defmock(ReportMock, for: EHealth.API.ReportBehaviour)
