Mox.defmock(ManMock, for: EHealth.API.ManBehaviour)
Mox.defmock(MPIMock, for: EHealth.API.MPIBehaviour)
Mox.defmock(MithrilMock, for: EHealth.API.MithrilBehaviour)
Mox.defmock(SignatureMock, for: EHealth.API.SignatureBehaviour)
Mox.defmock(OPSMock, for: EHealth.API.OPSBehaviour)
Mox.defmock(MediaStorageMock, for: EHealth.API.MediaStorageBehaviour)
