Mox.defmock(OPSMock, for: Core.API.OPSBehaviour)
Mox.defmock(ManMock, for: Core.API.ManBehaviour)
Mox.defmock(MPIMock, for: Core.API.MPIBehaviour)
Mox.defmock(MithrilMock, for: Core.API.MithrilBehaviour)
Mox.defmock(SignatureMock, for: Core.API.SignatureBehaviour)
Mox.defmock(MediaStorageMock, for: Core.API.MediaStorageBehaviour)
Mox.defmock(ReportMock, for: Core.API.ReportBehaviour)
Mox.defmock(OTPVerificationMock, for: Core.API.OTPVerificationBehaviour)
Mox.defmock(UAddressesMock, for: Core.API.UAddressesBehaviour)
Mox.defmock(CasherMock, for: Core.API.CasherBehaviour)

Mox.defmock(PostmarkMock, for: Core.API.PostmarkBehaviour)
Mox.defmock(DeclarationRequestsCreatorMock, for: Core.DeclarationRequests.API.CreatorBehaviour)
