-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 12:34:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `mpi_id` TEXT NOT NULL,
  `status` ENUM('') NOT NULL,
  `education[]` JSON NOT NULL,
  `certificates[]` JSON NOT NULL,
  `licenses[]` JSON NOT NULL,
  `jobs[]` JSON NULL,
  `created_at` DATETIME NOT NULL,
  `created_by` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `updated_by` TEXT GENERATED ALWAYS AS (),
  `active` TINYINT NULL,
  `name` TEXT NULL,
  PRIMARY KEY (`mpi_id`));


-- -----------------------------------------------------
-- Table `mydb`.`msp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`msp` (
  `id` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `short_name` TEXT NULL,
  `type` ENUM('') NOT NULL,
  `edrpou` TEXT NOT NULL,
  `services[]` JSON NOT NULL,
  `license` JSON NOT NULL,
  `accreditation` JSON NOT NULL,
  `addresses[]` JSON NULL,
  `phones[]` JSON NULL,
  `emails[]` JSON NULL,
  `created_at` DATETIME NOT NULL,
  `created_by` TEXT NOT NULL,
  `updated_at` DATETIME NULL,
  `updated_by` TEXT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`labour_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`labour_contract` (
  `id` TEXT NOT NULL,
  `doctor_id` TEXT NOT NULL,
  `msp_id` TEXT NOT NULL,
  `title` TEXT NOT NULL,
  `speciality` TEXT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  `active` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `created_by` TEXT NOT NULL,
  `updated_by` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Labour_Contract_Doctor_idx` (`doctor_id` ASC),
  INDEX `fk_Labour_Contract_MSP1_idx` (`msp_id` ASC),
  CONSTRAINT `fk_Labour_Contract_Doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`mpi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Labour_Contract_MSP1`
    FOREIGN KEY (`msp_id`)
    REFERENCES `mydb`.`msp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`declaration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`declaration` (
  `id` TEXT NOT NULL,
  `doctor_id` TEXT NOT NULL,
  `patient_id` TEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `msp_id` TEXT NOT NULL,
  `signature` TEXT NOT NULL,
  `certificate` TEXT NOT NULL,
  `status` ENUM('') NOT NULL,
  `signed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `created_by` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `updated_by` TEXT NOT NULL,
  `confident_person_id` TEXT NULL,
  `active` TINYINT NULL,
  `scope` ENUM('') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Declaration_MSP1_idx` (`msp_id` ASC),
  INDEX `fk_Declaration_Doctor1_idx` (`doctor_id` ASC),
  CONSTRAINT `fk_Declaration_MSP1`
    FOREIGN KEY (`msp_id`)
    REFERENCES `mydb`.`msp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Declaration_Doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`mpi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `parameters[]` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`capitation_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`capitation_contract` (
  `id` TEXT NOT NULL,
  `msp_id` TEXT NOT NULL,
  `product_id` TEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  `status` ENUM('') NOT NULL,
  `signed_at` DATETIME NULL,
  `services[]` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GPMD_Contract_MSP1_idx` (`msp_id` ASC),
  INDEX `fk_GPMD_Contract_Product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_GPMD_Contract_MSP1`
    FOREIGN KEY (`msp_id`)
    REFERENCES `mydb`.`msp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GPMD_Contract_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
