defmodule EHealth.API.OAuth do
  @moduledoc """
  Trump API client
  API documentation: http://docs.trump1.apiary.io
  """

  use HTTPoison.Base
  use Confex, otp_app: :ehealth

  alias Ecto.UUID
  alias EHealth.API.ResponseDecoder

  def process_url(url), do: config()[:endpoint] <> url

  def options, do: config()[:hackney_options]

  def process_request_headers(headers) do
    headers ++ [{"Content-Type", "application/json"}]
  end

  def create_client(client) do
    "/admin/clients"
    |> post!(prepare_client_data(client), [], options())
    |> ResponseDecoder.check_response()
  end

  def prepare_client_data(client) do
    client =
      client
      |> put_client_type_id()
      |> Map.merge(%{
        "redirect_uri" => "redirect_uri", # ToDo: set non required
        "secret" => UUID.generate() <> " !GENERATED BY API CLIENT!", # ToDo: set non required
      })

    Poison.encode!(%{"client" => client})
  end

  def put_client_type_id(client) do
    Map.put(client, "client_type_id", config()[:client_type_id])
  end
end
